### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by DecDuck** [kirypto-minecraft-mods/Grand-Sign-Shops#3]
Is there any sort of release for this mod? I don't mind beta-testing it

**Comment by kirypto** [comment]
Hey @DecDuck, thanks for showing interest! To be honest, I set aside this project a ways back... I think MC was in 1.15.2 when I was working on it. If I recall correctly, I got this to the point that it you could put a sign above a chest with a value on it, and it clicking on it would add/remove currency from your Grand-Economy balance. However, it wasn't yet interacting with items in the chest, and you could break the chest or sign and it would get really buggy. 

I would love to get back to this, but to be honest, I don't see being able to any time soon. If someone else wants to fork it and continue, I could offer advice and help, but I don't think I'll get this even to a beta in the foreseeable future.
